DROP TABLE  PROJECT_DATA_AUDIT ;


create table PROJECT_DATA_AUDIT 
(
project_id Number Not null,EMPLOYEE_PARTICIPANT_ID NUMBER NOT NULL,
PROJECT_LEADER_ID  NUMBER NOT NULL,ACTUAL_BUDGET NUMBER NOT NULL,ACTION_TYPE VARCHAR(50) NOT NULL,
ACTION_DATE DATE NOT NULL
);



CREATE OR REPLACE TRIGGER DBMS_AFTER_TRIGGER
AFTER UPDATE OR DELETE OR INSERT ON PROJECT_DATA
FOR EACH ROW
    BEGIN
     IF INSERTING THEN 
        INSERT INTO PROJECT_DATA_AUDIT(project_id, EMPLOYEE_PARTICIPANT_ID , PROJECT_LEADER_ID,ACTUAL_BUDGET,Action_type,ACTION_DATE)
        VALUES  (:new.project_id,:new.EMPLOYEE_PARTICIPANT_ID ,:new.PROJECT_LEADER_ID,:new.ACTUAL_BUDGET,'INSERT' ,SYSDATE);
     ELSIF UPDATING THEN
        INSERT INTO PROJECT_DATA_AUDIT(project_id, EMPLOYEE_PARTICIPANT_ID , PROJECT_LEADER_ID, ACTUAL_BUDGET,Action_type,ACTION_DATE)
        VALUES  (:new.project_id,:new.EMPLOYEE_PARTICIPANT_ID ,:new.PROJECT_LEADER_ID,:new.ACTUAL_BUDGET,'UPDATE' ,SYSDATE);
    ELSIF Deleting THEN
        INSERT INTO PROJECT_DATA_AUDIT(project_id, EMPLOYEE_PARTICIPANT_ID , PROJECT_LEADER_ID, ACTUAL_BUDGET,Action_type,ACTION_DATE)
        VALUES  (:old.project_id,:old.EMPLOYEE_PARTICIPANT_ID ,:old.PROJECT_LEADER_ID,:old.ACTUAL_BUDGET,'DELETE' ,SYSDATE);
    END IF;
END;